---
# tasks file for helloworld

- hosts: webservers
  tasks:
  - name: upgrade all packages
    become: yes
    yum: name=* state=latest

  - name: Installing node and npm
    become: yes
    yum:
      enablerepo: epel
      state: installed
      name:
      - nodejs
      - npm

  - name: Copying the upstart file
    become: yes
    copy:
      src: /home/ec2-user/swdv660/helloworld.conf
      dest: /etc/init/helloworld.conf
      owner: root
      group: root
      mode: 0644
  
  - name: Create Mongodb 4.0 Repo
    become: yes
    copy:
      src: /home/ec2-user/swdv660/mongodb-org-4.0.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: 0644

  - name: Installing Mongodb
    become: yes
    yum:
      enablerepo: epel
      state: installed
      name: mongodb

  - name: restart helloworld
    become: yes
    service:
      name: helloworld
      state: started


  - name: Copying the application file
    become: yes
    copy:
      src: /home/ec2-user/swdv660/helloworld.js
      dest: /home/ec2-user/
      owner: ec2-user
      group: ec2-user
      mode: 0644
    notify: restart helloworld