---
# tasks file for helloworld

- hosts: webservers
  tasks:
  - name: upgrade all packages
    become: yes
    yum: name=* state=latest

  - name: Installing node and npm
    become: yes
    yum:
      enablerepo: epel
      state: installed
      name:
      - nodejs
      - npm

  - name: Copying the application file
    copy:
      src: /home/ec2-user/swdv660/helloworld.js
      dest: /home/ec2-user/
      owner: ec2-user
      group: ec2-user
      mode: 0644
    notify: restart helloworld

  - name: Copying the upstart file
    become: yes
    copy:
      src: /home/ec2-user/swdv660/helloworld.conf
      dest: /etc/init/
      owner: root
      group: root
      mode: 0644
  
  - name: restart helloworld
    service: name=helloworld state=restarted
    become: yes
